const Bundesliga = [
  {image: require('../assets/bundesliga/1.jpg')},
  {image: require('../assets/bundesliga/2.jpg')},
  {image: require('../assets/bundesliga/3.jpg')},
  {image: require('../assets/bundesliga/4.jpg')},
  {image: require('../assets/bundesliga/5.jpg')},
  {image: require('../assets/bundesliga/6.jpg')},
  {image: require('../assets/bundesliga/7.jpg')},
  {image: require('../assets/bundesliga/8.jpg')},
  {image: require('../assets/bundesliga/9.jpg')},
  {image: require('../assets/bundesliga/10.jpg')},
  {image: require('../assets/bundesliga/11.jpg')},
  {image: require('../assets/bundesliga/12.jpg')},
  {image: require('../assets/bundesliga/13.jpg')},
  {image: require('../assets/bundesliga/14.jpg')},
  {image: require('../assets/bundesliga/15.jpg')},
  {image: require('../assets/bundesliga/16.jpg')},
  {image: require('../assets/bundesliga/17.jpg')},
  {image: require('../assets/bundesliga/18.jpg')},
];
export default Bundesliga;
