const InternationalFriendly = [
  {image: require('../assets/internationalFriendly/1.jpg')},
  {image: require('../assets/internationalFriendly/2.jpg')},
  {image: require('../assets/internationalFriendly/3.jpg')},
  {image: require('../assets/internationalFriendly/4.jpg')},
  {image: require('../assets/internationalFriendly/5.jpg')},
  {image: require('../assets/internationalFriendly/6.jpg')},
  {image: require('../assets/internationalFriendly/7.jpg')},
  {image: require('../assets/internationalFriendly/8.jpg')},
  {image: require('../assets/internationalFriendly/9.jpg')},
  {image: require('../assets/internationalFriendly/10.jpg')},
  {image: require('../assets/internationalFriendly/11.jpg')},
  {image: require('../assets/internationalFriendly/12.jpg')},
  {image: require('../assets/internationalFriendly/13.jpg')},
  {image: require('../assets/internationalFriendly/14.jpg')},
  {image: require('../assets/internationalFriendly/15.jpg')},
  {image: require('../assets/internationalFriendly/16.jpg')},
  {image: require('../assets/internationalFriendly/17.jpg')},
  {image: require('../assets/internationalFriendly/18.jpg')},
];
export default InternationalFriendly;
