const RolandGarros = [
  {id: '1', image: require('../assets/rolandGarros/1.jpg')},
  {id: '2', image: require('../assets/rolandGarros/2.jpg')},
  {id: '3', image: require('../assets/rolandGarros/3.jpg')},
  {id: '4', image: require('../assets/rolandGarros/4.jpg')},
  {id: '5', image: require('../assets/rolandGarros/5.jpg')},
  {id: '6', image: require('../assets/rolandGarros/6.jpg')},
  {id: '7', image: require('../assets/rolandGarros/7.jpg')},
  {id: '8', image: require('../assets/rolandGarros/8.jpg')},
  {id: '9', image: require('../assets/rolandGarros/9.jpg')},
  {id: '10', image: require('../assets/rolandGarros/10.jpg')},
  {id: '11', image: require('../assets/rolandGarros/11.jpg')},
  {id: '12', image: require('../assets/rolandGarros/12.jpg')},
  {id: '13', image: require('../assets/rolandGarros/13.jpg')},
  {id: '14', image: require('../assets/rolandGarros/14.jpg')},
  {id: '15', image: require('../assets/rolandGarros/15.jpg')},
  {id: '16', image: require('../assets/rolandGarros/16.jpg')},
  {id: '17', image: require('../assets/rolandGarros/17.jpg')},
  {id: '18', image: require('../assets/rolandGarros/18.jpg')},
];
export default RolandGarros;
