const SeaGames = [
  {image: require('../assets/seaGames/1.jpg')},
  {image: require('../assets/seaGames/2.jpg')},
  {image: require('../assets/seaGames/3.jpg')},
  {image: require('../assets/seaGames/4.jpg')},
  {image: require('../assets/seaGames/5.jpg')},
  {image: require('../assets/seaGames/6.jpg')},
  {image: require('../assets/seaGames/7.jpg')},
  {image: require('../assets/seaGames/8.jpg')},
  {image: require('../assets/seaGames/9.jpg')},
  {image: require('../assets/seaGames/10.jpg')},
  {image: require('../assets/seaGames/11.jpg')},
  {image: require('../assets/seaGames/12.jpg')},
  {image: require('../assets/seaGames/13.jpg')},
  {image: require('../assets/seaGames/14.jpg')},
  {image: require('../assets/seaGames/15.jpg')},
  {image: require('../assets/seaGames/16.jpg')},
  {image: require('../assets/seaGames/17.jpg')},
  {image: require('../assets/seaGames/18.jpg')},
];
export default SeaGames;
