const SerieA2023 = [
  {id: '1', image: require('../assets/serieA/1.png')},
  {id: '2', image: require('../assets/serieA/2.png')},
  {id: '3', image: require('../assets/serieA/3.png')},
  {id: '4', image: require('../assets/serieA/4.png')},
  {id: '5', image: require('../assets/serieA/5.png')},
  {id: '6', image: require('../assets/serieA/6.png')},
  {id: '7', image: require('../assets/serieA/7.png')},
  {id: '8', image: require('../assets/serieA/8.png')},
  {id: '9', image: require('../assets/serieA/9.png')},
  {id: '10', image: require('../assets/serieA/10.png')},
  {id: '11', image: require('../assets/serieA/11.png')},
  {id: '12', image: require('../assets/serieA/12.png')},
  {id: '13', image: require('../assets/serieA/13.png')},
  {id: '14', image: require('../assets/serieA/14.png')},
  {id: '15', image: require('../assets/serieA/15.png')},
  {id: '16', image: require('../assets/serieA/16.png')},
  {id: '17', image: require('../assets/serieA/17.png')},
  {id: '18', image: require('../assets/serieA/18.png')},
];
export default SerieA2023;
