const SportsTVShows = [
  {image: require('../assets/sportsTVshow/1.jpg')},
  {image: require('../assets/sportsTVshow/2.jpg')},
  {image: require('../assets/sportsTVshow/3.jpg')},
  {image: require('../assets/sportsTVshow/4.jpg')},
  {image: require('../assets/sportsTVshow/5.jpg')},
  {image: require('../assets/sportsTVshow/6.jpg')},
  {image: require('../assets/sportsTVshow/7.jpg')},
  {image: require('../assets/sportsTVshow/8.jpg')},
  {image: require('../assets/sportsTVshow/9.jpg')},
  {image: require('../assets/sportsTVshow/10.jpg')},
  {image: require('../assets/sportsTVshow/11.jpg')},
  {image: require('../assets/sportsTVshow/12.jpg')},
  {image: require('../assets/sportsTVshow/13.jpg')},
  {image: require('../assets/sportsTVshow/14.jpg')},
  {image: require('../assets/sportsTVshow/15.jpg')},
  {image: require('../assets/sportsTVshow/16.jpg')},
  {image: require('../assets/sportsTVshow/17.jpg')},
  {image: require('../assets/sportsTVshow/18.jpg')},
];
export default SportsTVShows;
