const TVChannels = [
  {image: require('../assets/tvChannels/1.jpg')},
  {image: require('../assets/tvChannels/2.jpg')},
  {image: require('../assets/tvChannels/3.jpg')},
  {image: require('../assets/tvChannels/4.jpg')},
  {image: require('../assets/tvChannels/5.jpg')},
  {image: require('../assets/tvChannels/6.jpg')},
  {image: require('../assets/tvChannels/7.jpg')},
  {image: require('../assets/tvChannels/8.jpg')},
  {image: require('../assets/tvChannels/9.jpg')},
  {image: require('../assets/tvChannels/10.jpg')},
  {image: require('../assets/tvChannels/11.jpg')},
  {image: require('../assets/tvChannels/12.jpg')},
  {image: require('../assets/tvChannels/13.jpg')},
  {image: require('../assets/tvChannels/14.jpg')},
  {image: require('../assets/tvChannels/15.jpg')},
  {image: require('../assets/tvChannels/16.jpg')},
  {image: require('../assets/tvChannels/17.jpg')},
  {image: require('../assets/tvChannels/18.jpg')},
  {image: require('../assets/tvChannels/19.jpg')},
  {image: require('../assets/tvChannels/20.jpg')},
  {image: require('../assets/tvChannels/21.jpg')},
];
export default TVChannels;
