const TVChannels = [
  {id: '3', image: require('../assets/tvChannels/3.jpg')},
  {id: '4', image: require('../assets/tvChannels/4.jpg')},
  {id: '5', image: require('../assets/tvChannels/5.jpg')},
  {id: '1', image: require('../assets/tvChannels/1.jpg')},
  {id: '2', image: require('../assets/tvChannels/2.jpg')},
  {id: '6', image: require('../assets/tvChannels/6.jpg')},
  {id: '7', image: require('../assets/tvChannels/7.jpg')},
  {id: '8', image: require('../assets/tvChannels/8.jpg')},
  {id: '9', image: require('../assets/tvChannels/9.jpg')},
  {id: '10', image: require('../assets/tvChannels/10.jpg')},
  {id: '11', image: require('../assets/tvChannels/11.jpg')},
  {id: '12', image: require('../assets/tvChannels/12.jpg')},
  {id: '13', image: require('../assets/tvChannels/13.jpg')},
  {id: '14', image: require('../assets/tvChannels/14.jpg')},
  {id: '15', image: require('../assets/tvChannels/15.jpg')},
  {id: '16', image: require('../assets/tvChannels/16.jpg')},
  {id: '17', image: require('../assets/tvChannels/17.jpg')},
  {id: '18', image: require('../assets/tvChannels/18.jpg')},
  {id: '19', image: require('../assets/tvChannels/19.jpg')},
  {id: '20', image: require('../assets/tvChannels/20.jpg')},
  {id: '21', image: require('../assets/tvChannels/21.jpg')},
];
export default TVChannels;
