const VTV = [
  {id: '1', image: require('../assets/vtv/1.jpg')},
  {id: '2', image: require('../assets/vtv/2.jpg')},
  {id: '3', image: require('../assets/vtv/3.jpg')},
  {id: '4', image: require('../assets/vtv/4.jpg')},
  {id: '5', image: require('../assets/vtv/5.jpg')},
  {id: '6', image: require('../assets/vtv/6.jpg')},
  {id: '7', image: require('../assets/vtv/7.jpg')},
  {id: '8', image: require('../assets/vtv/8.jpg')},
  {id: '9', image: require('../assets/vtv/9.jpg')},
  {id: '10', image: require('../assets/vtv/10.jpg')},
  {id: '11', image: require('../assets/vtv/11.jpg')},
  {id: '12', image: require('../assets/vtv/12.jpg')},
  {id: '13', image: require('../assets/vtv/13.jpg')},
  {id: '14', image: require('../assets/vtv/14.jpg')},
  {id: '15', image: require('../assets/vtv/15.jpg')},
  {id: '16', image: require('../assets/vtv/16.jpg')},
  {id: '17', image: require('../assets/vtv/17.jpg')},
  {id: '18', image: require('../assets/vtv/18.jpg')},
  {id: '19', image: require('../assets/vtv/19.jpg')},
  {id: '20', image: require('../assets/vtv/20.jpg')},
];
export default VTV;
